### PR TITLE
Allow sender address in WRAP and UNWRAP & more

### PR DESCRIPTION
**Pull request by fbeutin-ledger**
Allow sender address in WRAP and UNWRAP
Add support for clear sender address
Add associated tests
Bump ethereum SDK

### CODE REVIEW

**Comment by fbeutin-ledger** [comment]
Commit history is clean and PR is advised to be reviewed commit by commit

**Comment by fbeutin-ledger** [comment]
CI is failing for "Check SDK submodule version" because the plugin uses a dedicated branch with access to the derivation path

**Comment by fbeutin-ledger** [comment]
"ClusterFuzzLite PR fuzzing / PR" is failing because the fuzzer does not mock the OS crypto functions, not sure how to handle this I'll look into it later

**Review by cedelavergne-ledger — DISMISSED** [review]

**Comment by fbeutin-ledger** [comment]
I've left open for Donjon review but I'm deploying a test version on test provider in the meantime

**Review by bboilot-ledger — APPROVED** [review]

**Comment by fbeutin-ledger** [comment]
Merging this PR but still NOGO for prod, a followup PR will include Donjon remarks following Tech Doc sharing

**Pull request merged**
